"""
LLM Client — dual-provider abstraction for Claude (Anthropic) and Gemini (Google).
Handles answer generation and hallucination verification.
"""

from __future__ import annotations

import json
from typing import Optional

import config
from system_prompt import build_system_prompt


# ── Provider Clients (lazy-initialized) ──────────────────
_gemini_client = None
_anthropic_client = None


def _get_gemini_client():
    """Lazy-initialize the Gemini client."""
    global _gemini_client
    if _gemini_client is None:
        from google import genai
        _gemini_client = genai.Client(api_key=config.GEMINI_API_KEY)
    return _gemini_client


def _get_anthropic_client():
    """Lazy-initialize the Anthropic client."""
    global _anthropic_client
    if _anthropic_client is None:
        import anthropic
        _anthropic_client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
    return _anthropic_client


# ── Verifier Prompt ──────────────────────────────────────

VERIFIER_PROMPT = """\
You are a strict fact-checking engine. You will receive:
1. SOURCE_CHUNKS: The original source documents
2. GENERATED_ANSWER: A response generated by another AI

Your ONLY task: Does the GENERATED_ANSWER contain ANY claims, facts, or
interpretations that are NOT explicitly present in the SOURCE_CHUNKS?

Be extremely strict:
- Every claim must be traceable to a SOURCE_CHUNK.
- Every quote must be an exact or near-exact substring of a SOURCE_CHUNK.
- Any fabricated content not found in the sources should be flagged.
- If the answer merely summarizes what IS in the sources, that is acceptable.

Respond in JSON:
{"hallucinated": true/false, "reason": "Brief explanation"}"""


# ── Source Formatting ────────────────────────────────────

def _format_chunks_for_prompt(chunks: list[dict]) -> str:
    """Format retrieved chunks as source blocks for the prompt."""
    source_blocks = []
    for i, chunk in enumerate(chunks, 1):
        meta = chunk.get("metadata", {})
        book = meta.get("book_name", "Unknown")
        chapter = meta.get("chapter", "")
        page = meta.get("page_number", "")
        volume = meta.get("volume", "")

        header = f"[SOURCE {i}]"
        if book:
            header += f" [BOOK: {book}]"
        if chapter:
            header += f" [CHAPTER: {chapter}]"
        if page:
            header += f" [PAGE: {page}]"
        if volume:
            header += f" [VOLUME: {volume}]"

        source_blocks.append(f"{header}\n{chunk['text']}\n[END SOURCE {i}]")

    return "\n\n".join(source_blocks)


# ── Generation: Gemini ───────────────────────────────────

def _generate_gemini(query: str, sources_text: str, system_prompt: str,
                     conversation_history: list[dict] = None) -> dict:
    """Generate answer using Gemini."""
    from google.genai import types

    client = _get_gemini_client()

    # Build conversation with history
    contents = []
    if conversation_history:
        for turn in conversation_history:
            contents.append({
                "role": turn["role"],
                "parts": [{"text": turn["content"]}],
            })

    user_message = f"""Here are the SOURCE documents you MUST use to answer:

{sources_text}

---

USER QUERY: {query}

Remember: Answer using ONLY the sources above. Respond in the required JSON format. Maintain the persona voice."""

    contents.append({"role": "user", "parts": [{"text": user_message}]})

    response = client.models.generate_content(
        model=config.GEMINI_MODEL,
        contents=contents,
        config=types.GenerateContentConfig(
            system_instruction=system_prompt,
            temperature=config.TEMPERATURE,
            max_output_tokens=config.MAX_OUTPUT_TOKENS,
            response_mime_type="application/json",
        ),
    )

    return json.loads(response.text.strip())


# ── Generation: Claude ───────────────────────────────────

def _generate_claude(query: str, sources_text: str, system_prompt: str,
                     conversation_history: list[dict] = None) -> dict:
    """Generate answer using Claude."""
    client = _get_anthropic_client()

    # Build messages with history
    messages = []
    if conversation_history:
        for turn in conversation_history:
            role = "user" if turn["role"] == "user" else "assistant"
            messages.append({"role": role, "content": turn["content"]})

    user_message = f"""Here are the SOURCE documents you MUST use to answer:

{sources_text}

---

USER QUERY: {query}

Remember: Answer using ONLY the sources above. Respond in the required JSON format. Maintain the persona voice."""

    messages.append({"role": "user", "content": user_message})

    response = client.messages.create(
        model=config.CLAUDE_MODEL,
        max_tokens=config.MAX_OUTPUT_TOKENS,
        temperature=config.TEMPERATURE,
        system=system_prompt,
        messages=messages,
    )

    # Extract text from Claude response
    response_text = response.content[0].text.strip()
    return json.loads(response_text)


# ── Public API ───────────────────────────────────────────

def generate_answer(query: str, retrieved_chunks: list[dict],
                    conversation_history: list[dict] = None) -> dict:
    """
    Generate a persona-voiced answer grounded in source chunks.

    Args:
        query: User's question
        retrieved_chunks: Chunks from vector store search
        conversation_history: Previous turns for context (optional)

    Returns:
        Parsed JSON response dict with: can_answer, answer_text, citations[], etc.
    """
    system_prompt = build_system_prompt()
    sources_text = _format_chunks_for_prompt(retrieved_chunks)

    try:
        if config.LLM_PROVIDER == "claude":
            result = _generate_claude(query, sources_text, system_prompt, conversation_history)
        else:
            result = _generate_gemini(query, sources_text, system_prompt, conversation_history)

        # Ensure required fields
        result.setdefault("can_answer", False)
        result.setdefault("answer_text", "")
        result.setdefault("citations", [])
        result.setdefault("follow_up", "")
        result.setdefault("closing", "")

        return result

    except json.JSONDecodeError as e:
        print(f"  ✗ JSON parse error: {e}")
        return _empty_response()

    except Exception as e:
        print(f"  ✗ LLM API error ({config.LLM_PROVIDER}): {e}")
        return _empty_response()


def verify_answer(retrieved_chunks: list[dict], generated_answer: dict) -> bool:
    """
    Verification pass: checks if the generated answer is grounded in sources.

    Returns:
        True if grounded (no hallucination), False if hallucination detected
    """
    if not config.ENABLE_VERIFICATION:
        return True

    sources_text = _format_chunks_for_prompt(retrieved_chunks)
    answer_text = json.dumps(generated_answer, indent=2, ensure_ascii=False)

    verification_message = f"""SOURCE_CHUNKS:
{sources_text}

---

GENERATED_ANSWER:
{answer_text}

Does the GENERATED_ANSWER contain any claims not in the SOURCE_CHUNKS? Respond in JSON."""

    try:
        if config.LLM_PROVIDER == "claude":
            client = _get_anthropic_client()
            response = client.messages.create(
                model=config.CLAUDE_MODEL,
                max_tokens=256,
                temperature=0.0,
                system=VERIFIER_PROMPT,
                messages=[{"role": "user", "content": verification_message}],
            )
            response_text = response.content[0].text.strip()
        else:
            from google.genai import types
            client = _get_gemini_client()
            response = client.models.generate_content(
                model=config.GEMINI_MODEL,
                contents=[{"role": "user", "parts": [{"text": verification_message}]}],
                config=types.GenerateContentConfig(
                    system_instruction=VERIFIER_PROMPT,
                    temperature=0.0,
                    max_output_tokens=256,
                    response_mime_type="application/json",
                ),
            )
            response_text = (response.text or "").strip()

        if not response_text:
            print("  ⚠ Verification returned empty — passing by default")
            return True

        result = json.loads(response_text)
        hallucinated = result.get("hallucinated", False)

        if hallucinated:
            print(f"  ⚠ Verification FAILED: {result.get('reason', 'Unknown')}")
            return False

        print("  ✓ Verification passed: answer is grounded")
        return True

    except Exception as e:
        print(f"  ⚠ Verification error: {e} — passing by default")
        return True


def _empty_response() -> dict:
    """Return a blank response dict."""
    from system_prompt import load_persona
    try:
        persona = load_persona()
        refusal = persona.get("refusal_style", "I cannot address this matter.")
        closing = persona.get("closing", "")
    except Exception:
        refusal = "I cannot address this matter."
        closing = ""

    return {
        "can_answer": False,
        "answer_text": refusal,
        "citations": [],
        "follow_up": "",
        "closing": closing,
    }
