/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./static/**/*.{html,js}"],
  theme: {
      extend: {
          colors: {
              "on-primary-fixed-variant": "#574500",
              "surface-bright": "#38393e",
              "secondary-container": "#474742",
              "surface-dim": "#121317",
              "on-secondary-fixed-variant": "#474742",
              "outline": "#919095",
              "on-surface": "#e3e2e8",
              "on-error-container": "#ffdad6",
              "on-secondary-fixed": "#1c1c18",
              "primary-fixed": "#ffe088",
              "on-tertiary-fixed-variant": "#891d12",
              "tertiary-container": "#240000",
              "on-primary-container": "#957700",
              "surface-container-lowest": "#0d0e12",
              "on-tertiary-fixed": "#410000",
              "surface-tint": "#e9c349",
              "secondary": "#c9c6c0",
              "on-primary": "#3c2f00",
              "on-secondary-container": "#b7b5af",
              "surface-container-low": "#1a1b20",
              "surface-container": "#1f1f24",
              "surface-variant": "#343439",
              "on-background": "#e3e2e8",
              "background": "#121317",
              "error-container": "#93000a",
              "surface-container-high": "#292a2e",
              "on-surface-variant": "#c7c6cb",
              "on-tertiary": "#680201",
              "on-error": "#690005",
              "tertiary-fixed-dim": "#ffb4a8",
              "on-secondary": "#31312c",
              "primary-container": "#110b00",
              "surface-container-highest": "#343439",
              "primary": "#e9c349",
              "inverse-surface": "#e3e2e8",
              "primary-fixed-dim": "#e9c349",
              "tertiary": "#ffb4a8",
              "secondary-fixed-dim": "#c9c6c0",
              "on-primary-fixed": "#241a00",
              "inverse-on-surface": "#2f3035",
              "tertiary-fixed": "#ffdad4",
              "inverse-primary": "#735c00",
              "secondary-fixed": "#e5e2db",
              "surface": "#121317",
              "error": "#ffb4ab",
              "outline-variant": "#46464b",
              "on-tertiary-container": "#d0503f"
          },
          fontFamily: {
              "headline": ["Noto Serif"],
              "body": ["Inter"],
              "label": ["Inter"]
          },
          borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
      },
  },
  plugins: [],
}
