"""
API — FastAPI backend serving the RAG pipeline and web chatbot.
Provides endpoints for chat, persona info, sources, and session export.
Also serves the static web frontend.

Pipeline flow:
  analyze_intent (Router / fast model)
    ├─ casual query → generate_direct_answer (120b, no RAG, no Verifier)
    └─ rag query    → vector retrieval → generate_answer → verify_answer
"""

import logging
import asyncio
import datetime
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse, PlainTextResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Optional

import core.config as config
import core.vector_store as vector_store
import core.llm_client as llm_client
import core.session_manager as session_manager

logger = logging.getLogger(__name__)


# ── Lifespan Context ──────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    FastAPI Lifespan manager.
    - Pre-warms/connects the active Vector database (ChromaDB or PostgreSQL).
    - Spawns a background cooperative loop acting as an hourly scheduler 
      to dispatch daily motivation reminders/broadcasts (e.g. at 08:00 AM local).
    """
    store_type = config.VECTOR_STORE_TYPE.capitalize()
    print(f"\n🗄️  Initializing {store_type} Vector Store...")
    vector_store.initialize()

    # ── Start Hourly Broadcast Scheduler Loop ─────────────────────
    async def scheduler_loop():
        """
        Background hourly worker that triggers the motivation broadcast script.
        Checks once per hour to find users whose timezone-adjusted time matches 08:00 AM.
        """
        from broadcast_motivation import run_broadcast_for_hour
        
        print(f"⏰ Scheduler: Active (Checking hourly for 08:00 AM local time delivery).")
        while True:
            now = datetime.datetime.now(datetime.timezone.utc)
            # Hand off the logic to broadcast_motivation to resolve local user timezones
            try:
                await run_broadcast_for_hour(now.hour)
            except Exception as e:
                logger.error(f"Scheduler Error: {e}")
            
            # Sleep for 1 hour
            await asyncio.sleep(3600)

    # Schedule non-blocking execution inside the async event loop
    asyncio.create_task(scheduler_loop())
    
    yield
    print("\n👋 Resurrection Agent shutting down...")


# ── App Definition & Middleware ───────────────────────────────

app = FastAPI(
    title="Resurrection Agent",
    description="Historical Persona RAG Chatbot SaaS Node",
    lifespan=lifespan,
)

# CORS Policy allows cross-origin communication for federated client UIs
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Pydantic Request / Response Validation Models ─────────────

class ChatRequest(BaseModel):
    """Schema validating incoming message inquiries."""
    query: str = Field(..., description="The user's query or message.")
    system_prompt: str = Field(..., description="System instructions enforcing the persona's voice and boundaries.")
    death_date_ah: str = Field(..., description="Historical death date (AH) used to construct/detect anachronisms.")
    session_id: Optional[str] = Field(None, description="UUID or identifier for chat context persistence.")
    language: str = Field("EN", description="Primary preferred language of the conversation.")
    timezone: int = Field(7, description="Timezone offset (UTC offset) for time-aware triggers.")


class Citation(BaseModel):
    """Grounding citation schema showing document mapping."""
    book: str = ""
    volume: str = ""      # e.g., "Vol. 1" for multi-volume classics like the Ihya'
    chapter: str = ""     # Sub-section title/identifier if available
    page_number: str = "" # Page reference of the source text
    quote: str = ""       # Precise text extract from the historical source

    @classmethod
    def from_llm(cls, data: dict) -> "Citation":
        """Construct from LLM output dictionaries, coercing None fields to empty strings."""
        return cls(
            book=data.get("book") or "",
            volume=str(data.get("volume") or ""),
            chapter=data.get("chapter") or "",
            page_number=str(data.get("page_number") or ""),
            quote=data.get("quote") or "",
        )


class ChatResponse(BaseModel):
    """Strictly typed response returning generation output and validation telemetry."""
    answer_text: str = Field(..., description="The main content generated by the persona.")
    can_answer: bool = Field(..., description="Indicates if the query was successfully grounded in classical text.")
    citations: list[Citation] = Field(default_factory=list, description="Grounding source citations.")
    follow_up: str = Field("", description="Conversation continuation prompt in persona's voice.")
    closing: str = Field("", description="Persona signature or closing blessing.")
    session_id: str = Field("", description="The persistent session context key.")
    persona_name: str = Field("", description="Name of the persona currently answering.")


class ExportRequest(BaseModel):
    """Schema validating request to export chat history."""
    session_id: str = Field(..., description="The context session key to serialize.")
    format: str = Field("json", description="Desired export layout ('json' or 'markdown').")


class SubscriptionRequest(BaseModel):
    """Schema managing daily motivation scheduler registrations."""
    chat_id: str = Field(..., description="Telegram Chat ID or unique subscription key.")
    status: bool = Field(..., description="True to subscribe, False to opt-out.")


# ── REST API Endpoints ────────────────────────────────────────

@app.get("/api/health")
async def health():
    """
    Liveness and configuration diagnostics check.
    Returns: Dict containing server status and the default generative model name.
    """
    return {"status": "ok", "provider": config.OPENROUTER_MODEL}


@app.get("/api/persona")
async def persona():
    """
    Returns empty placeholder persona info for headless mode configurations.
    """
    return {"name": "SaaS Platform", "description": "Core routing backend"}


@app.get("/api/v1/{tenant_id}/sources")
async def sources(tenant_id: str):
    """
    Retrieves statistical information about files currently ingested for a tenant.
    Args:
        tenant_id: The specific bot/persona database scope.
    """
    stats = vector_store.get_source_stats(tenant_id)
    return stats


@app.post("/api/v1/{tenant_id}/subscribe")
async def subscribe(tenant_id: str, req: SubscriptionRequest):
    """
    Registers or modifies a user's subscription state for daily motivational broadcasts.
    """
    vector_store.toggle_subscription(tenant_id, req.chat_id, req.status)
    return {"status": "ok", "is_subscribed": req.status}


@app.post("/api/v1/{tenant_id}/chat", response_model=ChatResponse)
async def chat(tenant_id: str, req: ChatRequest):
    """
    SaaS Chat processing endpoint. Coordinates RAG intent routing, contextual retrieval,
    knowledge grounding, anachronism protection, and generation.

    Execution Flow:
      1. Fetch/Create persistent memory context scoped by tenant.
      2. Autoregisters numerical sessions (Telegram IDs) for time-aware motivations.
      3. Intent Routing -> Determing if conversational chat vs thematic query.
      4a. Fast Path (requires_rag=False) -> Skip retrieval & verifier, generate conversational reply.
      4b. RAG Path (requires_rag=True) -> Embed search query, execute multi-layer/broad index scan.
      5. Grounding Verification -> Validate responses to block hallucinations or anachronisms.
    """
    # ── 1. Scoped Session Persistence ─────────────────────────────
    session_id = session_manager.get_or_create_session(tenant_id, req.session_id)
    history = session_manager.get_history(session_id)

    # ── 2. Automatic Subscriber Registration ──────────────────────
    # Auto-registers numerical session IDs (typical Telegram chat IDs) for notifications
    if req.session_id and req.session_id.isdigit():
        try:
            vector_store.register_user(tenant_id, req.session_id, req.language, req.timezone)
        except Exception as e:
            logger.warning(f"Failed to register user: {e}")

    try:
        # ── 3. Intent Routing Analysis ────────────────────────────
        # Fast model routes query into casual conversation vs complex domain extraction
        router_output = llm_client.analyze_intent(req.query, history)
        intent = router_output.get("intent", "general_question")
        requires_rag = router_output.get("requires_rag", True)
        search_query = router_output.get("search_string", req.query)

        # ── 4a. Casual Fast Path (No Retrieval, No Grounding check) 
        if not requires_rag:
            print(f"  ⚡ Casual fast path: intent='{intent}' — skipping RAG and Verifier")
            result = llm_client.generate_answer(
                req.query,
                retrieved_chunks=[],        # Casual chat does not require source documents
                system_prompt=req.system_prompt,
                conversation_history=history,
                intent=intent,
            )
            # Add turns to memory and perform routine TTL garbage cleanup
            session_manager.add_turn(session_id, "user", req.query)
            session_manager.add_turn(session_id, "assistant", result.get("answer_text", ""))
            session_manager.cleanup_expired()
            return ChatResponse(
                answer_text=result.get("answer_text", ""),
                can_answer=result.get("can_answer", True),
                citations=[],
                follow_up=result.get("follow_up", ""),
                closing=result.get("closing", ""),
                session_id=session_id,
            )

        # ── 4b. RAG Path: Domain Grounded Generation ──────────────────
        # Check tenant database status before committing resources to retrieval
        if not vector_store.is_ingested(tenant_id):
            return ChatResponse(
                answer_text="No source texts have been linked to this persona. The administrator needs to run the ingestion script.",
                can_answer=False,
                session_id=session_id,
            )

        # Evaluate query length. Complex keywords/longer sentences trigger multi-layer expansion.
        is_complex = len(search_query) > 60
        if is_complex:
            print(f"  🔍 Multi-layer retrieval (complex query, {len(search_query)} chars)")
            retrieved_chunks = vector_store.query_multilayer(
                tenant_id=tenant_id,
                text=search_query,
                death_date_ah=req.death_date_ah,
                top_k=config.TOP_K
            )
        else:
            retrieved_chunks = vector_store.query(
                tenant_id=tenant_id,
                text=search_query,
                death_date_ah=req.death_date_ah,
                top_k=config.TOP_K
            )

        # Fallback if search engine yields absolutely zero matched documents
        if not retrieved_chunks:
            return ChatResponse(
                answer_text="I cannot address this query from my documented works.",
                can_answer=False,
                session_id=session_id,
            )

        # Generate grounding-constrained response based on context chunks
        result = llm_client.generate_answer(
            req.query, retrieved_chunks, req.system_prompt, history, intent=intent
        )

        # ── 5. Grounding & Anachronism Verification Check ─────────────
        # Safeguards persona by cross-checking sources and blocking dates after death_date_ah
        if result.get("can_answer") and config.ENABLE_VERIFICATION:
            is_grounded = llm_client.verify_answer(retrieved_chunks, result)
            if not is_grounded:
                result["can_answer"] = False
                result["answer_text"] = "I prefer not to provide an unverified answer, this is beyond my knowledge."
                result["citations"] = []

        # Store historical chat turns in the session database
        session_manager.add_turn(session_id, "user", req.query)
        session_manager.add_turn(session_id, "assistant", result.get("answer_text", ""))
        session_manager.cleanup_expired()

        return ChatResponse(
            answer_text=result["answer_text"],
            can_answer=result["can_answer"],
            citations=[Citation.from_llm(c) for c in result["citations"]],
            follow_up=result["follow_up"],
            closing=result["closing"],
            session_id=session_id,
        )

    except Exception as e:
        logger.error(f"Chat error: {e}", exc_info=True)
        return ChatResponse(
            answer_text="An error occurred while processing your question. Please try again.",
            can_answer=False,
            session_id=session_id,
        )


@app.post("/api/v1/export")
async def export_chat(req: ExportRequest):
    """
    Exports a user session's conversation history.
    Supports either structure-preserving JSON or rich human-readable Markdown format.
    """
    if req.format == "markdown":
        md_text = session_manager.export_session_markdown(req.session_id, "Persona")
        return PlainTextResponse(md_text, media_type="text/markdown")
    else:
        data = session_manager.export_session(req.session_id, "Persona")
        return JSONResponse(data)

