"""
LLM Client — dual-provider abstraction for Claude (Anthropic) and Gemini (Google).
Handles answer generation and hallucination verification.
"""

from __future__ import annotations

import json
from typing import Optional

import core.config as config


# ── Provider Clients (lazy-initialized) ──────────────────
_gemini_client = None
_anthropic_client = None
_openrouter_client = None


def _get_gemini_client():
    """Lazy-initialize the Gemini client."""
    global _gemini_client
    if _gemini_client is None:
        from google import genai
        _gemini_client = genai.Client(api_key=config.GEMINI_API_KEY)
    return _gemini_client


def _get_anthropic_client():
    """Lazy-initialize the Anthropic client."""
    global _anthropic_client
    if _anthropic_client is None:
        import anthropic
        _anthropic_client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
    return _anthropic_client


def _get_openrouter_client():
    """Lazy-initialize the OpenRouter client."""
    global _openrouter_client
    if _openrouter_client is None:
        import openai
        _openrouter_client = openai.OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=config.OPENROUTER_API_KEY,
        )
    return _openrouter_client


# ── Verifier Prompt ──────────────────────────────────────

VERIFIER_PROMPT = """\
You are a strict fact-checking engine. You will receive:
1. SOURCE_CHUNKS: The original source documents
2. GENERATED_ANSWER: A response generated by another AI

Your ONLY task: Does the GENERATED_ANSWER contain ANY claims, facts, or
interpretations that are NOT explicitly present in the SOURCE_CHUNKS?

Be extremely strict:
- Every claim must be traceable to a SOURCE_CHUNK.
- Every quote must be an exact or near-exact substring of a SOURCE_CHUNK.
- Any fabricated content not found in the sources should be flagged.
- If the answer merely summarizes what IS in the sources, that is acceptable.

Respond in JSON:
{"hallucinated": true/false, "reason": "Brief explanation"}"""


# ── Source Formatting ────────────────────────────────────

def _format_chunks_for_prompt(chunks: list[dict]) -> str:
    """Format retrieved chunks as source blocks for the prompt."""
    source_blocks = []
    for i, chunk in enumerate(chunks, 1):
        meta = chunk.get("metadata", {})
        book = meta.get("book_name", "Unknown")
        chapter = meta.get("chapter", "")
        page = meta.get("page_number", "")
        volume = meta.get("volume", "")

        header = f"[SOURCE {i}]"
        if book:
            header += f" [BOOK: {book}]"
        if chapter:
            header += f" [CHAPTER: {chapter}]"
        if page:
            header += f" [PAGE: {page}]"
        if volume:
            header += f" [VOLUME: {volume}]"

        source_blocks.append(f"{header}\n{chunk['text']}\n[END SOURCE {i}]")

    return "\n\n".join(source_blocks)


# ── Generation: Gemini ───────────────────────────────────

def _generate_gemini(query: str, sources_text: str, system_prompt: str,
                     conversation_history: list[dict] = None) -> dict:
    """Generate answer using Gemini."""
    from google.genai import types

    client = _get_gemini_client()

    # Build conversation with history
    contents = []
    if conversation_history:
        for turn in conversation_history:
            contents.append({
                "role": turn["role"],
                "parts": [{"text": turn["content"]}],
            })

    user_message = f"""Here are the SOURCE documents you MUST use to answer:

{sources_text}

---

USER QUERY: {query}

Remember: Answer using ONLY the sources above. Respond in the required JSON format. Maintain the persona voice."""

    contents.append({"role": "user", "parts": [{"text": user_message}]})

    response = client.models.generate_content(
        model=config.GEMINI_MODEL,
        contents=contents,
        config=types.GenerateContentConfig(
            system_instruction=system_prompt,
            temperature=config.TEMPERATURE,
            max_output_tokens=config.MAX_OUTPUT_TOKENS,
            response_mime_type="application/json",
        ),
    )

    return json.loads(response.text.strip())


# ── Generation: Claude ───────────────────────────────────

def _generate_claude(query: str, sources_text: str, system_prompt: str,
                     conversation_history: list[dict] = None) -> dict:
    """Generate answer using Claude."""
    client = _get_anthropic_client()

    # Build messages with history
    messages = []
    if conversation_history:
        for turn in conversation_history:
            role = "user" if turn["role"] == "user" else "assistant"
            messages.append({"role": role, "content": turn["content"]})

    user_message = f"""Here are the SOURCE documents you MUST use to answer:

{sources_text}

---

USER QUERY: {query}

Remember: Answer using ONLY the sources above. Respond in the required JSON format. Maintain the persona voice."""

    messages.append({"role": "user", "content": user_message})

    response = client.messages.create(
        model=config.CLAUDE_MODEL,
        max_tokens=config.MAX_OUTPUT_TOKENS,
        temperature=config.TEMPERATURE,
        system=system_prompt,
        messages=messages,
    )

    # Extract text from Claude response
    response_text = response.content[0].text.strip()
    return json.loads(response_text)


# ── Generation: OpenRouter ───────────────────────────────

def _generate_openrouter(query: str, sources_text: str, system_prompt: str,
                         conversation_history: list[dict] = None) -> dict:
    """Generate answer using OpenRouter."""
    client = _get_openrouter_client()

    # Build messages with history
    messages = [{"role": "system", "content": system_prompt}]
    if conversation_history:
        for turn in conversation_history:
            role = "user" if turn["role"] == "user" else "assistant"
            messages.append({"role": role, "content": turn["content"]})

    user_message = f"""Here are the SOURCE documents you MUST use to answer:

{sources_text}

---

USER QUERY: {query}

Remember: Answer using ONLY the sources above. Respond in the required JSON format. Maintain the persona voice."""

    messages.append({"role": "user", "content": user_message})

    response = client.chat.completions.create(
        model=config.OPENROUTER_MODEL,
        messages=messages,
        temperature=config.TEMPERATURE,
        max_tokens=config.MAX_OUTPUT_TOKENS,
        response_format={"type": "json_object"},
    )

    response_text = response.choices[0].message.content.strip()
    return json.loads(response_text)


# ── Query Rewriting ──────────────────────────────────────

REWRITER_PROMPT = """\
You are an expert Islamic theologian acting as a search engine librarian.
Your task is to take a conversational user query and chat history, and rewrite it into a dense, standalone search string.
The output will be embedded into vectors and matched against classical Arabic theological texts.

Rules:
1. Translate casual pronouns ("it", "he", "this concept") into the actual subject from the chat history.
2. If the user uses slang or modern terms, include the formal Arabic equivalent (e.g., "heart" -> "Qalb", "logic" -> "Mantiq").
3. DO NOT output conversational filler. No "Here is the query" or "Search string:".
4. ONLY output the bare optimized search string.
"""

def rewrite_query(query: str, conversation_history: list[dict] = None) -> str:
    """Rewrite conversational queries into dense search strings."""
    if not conversation_history:
        return query  # Nothing to contextualize if it's the first question
    
    # We only care about the last few turns
    history_str = ""
    for turn in conversation_history[-4:]:
        role = "User" if turn["role"] == "user" else "Al-Ghazali"
        # Truncate AI answers so prompt doesn't get too bloated
        content = turn["content"][:300] + "..." if len(turn["content"]) > 300 else turn["content"]
        history_str += f"{role}: {content}\n"
        
    user_prompt = f"""CHAT HISTORY:
{history_str}

CURRENT USER QUERY:
{query}

Rewrite the CURRENT USER QUERY into a highly specific standalone search string based on the context above."""

    try:
        client = _get_openrouter_client()
        response = client.chat.completions.create(
            model=config.REWRITER_MODEL,
            messages=[
                {"role": "system", "content": REWRITER_PROMPT},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.0,
            max_tokens=60,
        )
        rewritten = response.choices[0].message.content.strip()
        
        # Fallback cleanup if the model hallucinates a conversational prefix
        for prefix in ["Here is the", "Search string:", "Rewritten:", "Optimized:"]:
            if rewritten.lower().startswith(prefix.lower()):
                rewritten = rewritten[len(prefix):].strip()
        
        # Remove quotes if the model wrapped the output
        rewritten = rewritten.strip('"\'')
        print(f"  🔄 Rewritten query: '{rewritten}' (Original: '{query}')")
        return rewritten

    except Exception as e:
        print(f"  ⚠ Rewriter error: {e}. Falling back to original query.")
        return query


# ── Public API ───────────────────────────────────────────

def generate_answer(query: str, retrieved_chunks: list[dict], system_prompt: str,
                    conversation_history: list[dict] = None) -> dict:
    """
    Generate a persona-voiced answer grounded in source chunks.

    Args:
        query: User's question
        retrieved_chunks: Chunks from vector store search
        system_prompt: The detailed persona ruleset
        conversation_history: Previous turns for context (optional)

    Returns:
        Parsed JSON response dict with: can_answer, answer_text, citations[], etc.
    """
    sources_text = _format_chunks_for_prompt(retrieved_chunks)

    # ── Input Length Enforcement ─────────────────────────────
    # Approximation: 4 chars ≈ 1 token (conservative for mixed Arabic/English)
    full_prompt_len = len(query) + len(sources_text) + len(system_prompt)
    if conversation_history:
        full_prompt_len += sum(len(turn["content"]) for turn in conversation_history)

    estimated_tokens = full_prompt_len // 4
    if estimated_tokens > config.MAX_INPUT_TOKENS:
        print(f"  ✗ Input limit exceeded: ~{estimated_tokens} tokens vs max {config.MAX_INPUT_TOKENS}")
        return _empty_response()

    try:
        if config.LLM_PROVIDER == "claude":
            result = _generate_claude(query, sources_text, system_prompt, conversation_history)
        elif config.LLM_PROVIDER == "openrouter":
            result = _generate_openrouter(query, sources_text, system_prompt, conversation_history)
        else:
            result = _generate_gemini(query, sources_text, system_prompt, conversation_history)

        # ── Normalize Response ───────────────────────────────────
        # Handle variations in field names from different models (Nemotron uses 'response' or 'answer')
        if "answer" in result and not result.get("answer_text"):
            result["answer_text"] = result["answer"]
        if "response" in result and not result.get("answer_text"):
            result["answer_text"] = result["response"]
            
        if result.get("answer_text") and not result.get("can_answer"):
            # If the model gave an answer but forgot to set the boolean
            result["can_answer"] = True

        # Ensure required fields exist
        result.setdefault("can_answer", False)
        result.setdefault("answer_mode", "elaborated")
        result.setdefault("quote_primary", "")
        result.setdefault("answer_text", "")
        result.setdefault("citations", [])
        result.setdefault("follow_up", "")
        result.setdefault("closing", "")

        return result

    except json.JSONDecodeError as e:
        print(f"  ✗ JSON parse error: {e}")
        return _empty_response()

    except Exception as e:
        print(f"  ✗ LLM API error ({config.LLM_PROVIDER}): {e}")
        return _empty_response()


def verify_answer(retrieved_chunks: list[dict], generated_answer: dict) -> bool:
    """
    Verification pass: checks if the generated answer is grounded in sources.

    Returns:
        True if grounded (no hallucination), False if hallucination detected
    """
    if not config.ENABLE_VERIFICATION:
        return True

    sources_text = _format_chunks_for_prompt(retrieved_chunks)
    answer_text = json.dumps(generated_answer, indent=2, ensure_ascii=False)

    verification_message = f"""SOURCE_CHUNKS:
{sources_text}

---

GENERATED_ANSWER:
{answer_text}

Does the GENERATED_ANSWER contain any claims not in the SOURCE_CHUNKS? Respond in JSON."""

    try:
        if config.LLM_PROVIDER == "claude":
            client = _get_anthropic_client()
            response = client.messages.create(
                model=config.CLAUDE_MODEL,
                max_tokens=256,
                temperature=0.0,
                system=VERIFIER_PROMPT,
                messages=[{"role": "user", "content": verification_message}],
            )
            response_text = response.content[0].text.strip()
        elif config.LLM_PROVIDER == "openrouter":
            client = _get_openrouter_client()
            response = client.chat.completions.create(
                model=config.OPENROUTER_MODEL,
                temperature=0.0,
                max_tokens=256,
                messages=[
                    {"role": "system", "content": VERIFIER_PROMPT},
                    {"role": "user", "content": verification_message}
                ],
                response_format={"type": "json_object"},
            )
            response_text = response.choices[0].message.content.strip()
        else:
            from google.genai import types
            client = _get_gemini_client()
            response = client.models.generate_content(
                model=config.GEMINI_MODEL,
                contents=[{"role": "user", "parts": [{"text": verification_message}]}],
                config=types.GenerateContentConfig(
                    system_instruction=VERIFIER_PROMPT,
                    temperature=0.0,
                    max_output_tokens=256,
                    response_mime_type="application/json",
                ),
            )
            response_text = (response.text or "").strip()

        if not response_text:
            print("  ⚠ Verification returned empty — passing by default")
            return True

        result = json.loads(response_text)
        hallucinated = result.get("hallucinated", False)

        if hallucinated:
            print(f"  ⚠ Verification FAILED: {result.get('reason', 'Unknown')}")
            return False

        print("  ✓ Verification passed: answer is grounded")
        return True

    except Exception as e:
        print(f"  ⚠ Verification error: {e} — passing by default")
        return True


def _empty_response() -> dict:
    """Return a blank response dict."""
    refusal = "I cannot address this matter."
    closing = ""

    return {
        "can_answer": False,
        "answer_text": refusal,
        "citations": [],
        "follow_up": "",
        "closing": closing,
    }
