"""
LLM Client — OpenRouter-only abstraction.
Handles query rewriting (fast model), answer generation (large model),
and hallucination + anachronism verification (fast model).
"""

from __future__ import annotations

import json

import core.config as config


# ── Provider Client (lazy-initialized) ───────────────────
_openrouter_client = None


def _get_openrouter_client():
    """Lazy-initialize the OpenRouter client."""
    global _openrouter_client
    if _openrouter_client is None:
        import openai
        _openrouter_client = openai.OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=config.OPENROUTER_API_KEY,
        )
    return _openrouter_client


# ── Prompts ───────────────────────────────────────────────

VERIFIER_PROMPT = """\
You are a fact-checking engine. You will receive:
1. SOURCE_CHUNKS: The original source documents
2. GENERATED_ANSWER: A response generated by another AI

Your task is to ensure the GENERATED_ANSWER is grounded in the SOURCE_CHUNKS.

Rules:
- The answer may draw philosophical parallels or bridge concepts, provided the core themes and cited quotes exist in the SOURCE_CHUNKS.
- Ensure that any direct quote in the answer is a valid substring of a SOURCE_CHUNK.
- Flag as hallucinated ONLY if the answer invents historical facts, completely fabricates quotes, or makes claims that directly contradict the provided sources.
- Do NOT flag the answer as hallucinated just because it uses a conversational or philosophical tone.
- ANACHRONISM CHECK: Flag as hallucinated if the answer mentions any person, event, or invention that occurred AFTER 505 AH / 1111 CE (e.g. mentions of Ibn Taymiyya, Rumi, modern science, or later history).

Respond in JSON:
{"hallucinated": true/false, "reason": "Brief explanation"}"""

REWRITER_PROMPT = """\
You are an expert Islamic theologian acting as a search engine librarian.
Your task is to take a conversational user query and chat history, and rewrite it into a highly efficient, token-optimized, and highly accurate standalone search string.
The output will be embedded into vectors and matched against classical Arabic theological texts.

Rules:
1. Translate casual pronouns ("it", "he", "this concept") into the actual subject from the chat history.
2. If the user uses slang or modern terms, include the formal Arabic equivalent (e.g., "heart" -> "Qalb", "logic" -> "Mantiq").
3. DO NOT output conversational filler. No "Here is the query" or "Search string:".
4. Optimize for token efficiency: eliminate redundant words while preserving maximum semantic accuracy.
5. ONLY output the bare optimized search string.
"""

# Known conversational prefixes the model may hallucinate before the search string
_REWRITER_PREFIXES = ["Here is the", "Search string:", "Rewritten:", "Optimized:"]


# ── Source Formatting ─────────────────────────────────────

def _format_chunks_for_prompt(chunks: list[dict]) -> str:
    """Format retrieved chunks as numbered source blocks for the prompt."""
    source_blocks = []
    for i, chunk in enumerate(chunks, 1):
        meta = chunk.get("metadata", {})
        book    = meta.get("book_name", "Unknown")
        chapter = meta.get("chapter", "")
        page    = meta.get("page_number", "")
        volume  = meta.get("volume", "")

        header = f"[SOURCE {i}]"
        if book:    header += f" [BOOK: {book}]"
        if volume:  header += f" [VOLUME: {volume}]"
        if chapter: header += f" [CHAPTER: {chapter}]"
        if page:    header += f" [PAGE: {page}]"

        source_blocks.append(f"{header}\n{chunk['text']}\n[END SOURCE {i}]")

    return "\n\n".join(source_blocks)


def _build_user_message(query: str, sources_text: str) -> str:
    """Build the shared user-turn message injected into every generation call."""
    return (
        f"Here are the SOURCE documents you MUST use to answer:\n\n{sources_text}\n\n---\n\n"
        f"USER QUERY: {query}\n\n"
        f"Remember: Answer using ONLY the sources above. Respond in the required JSON format. Maintain the persona voice."
    )


# ── Generation ────────────────────────────────────────────

def _generate_openrouter(query: str, sources_text: str, system_prompt: str,
                         conversation_history: list[dict] = None) -> dict:
    """Generate answer using OpenRouter."""
    client = _get_openrouter_client()

    messages = [{"role": "system", "content": system_prompt}]
    if conversation_history:
        for turn in conversation_history:
            role = "user" if turn["role"] == "user" else "assistant"
            messages.append({"role": role, "content": turn["content"]})

    messages.append({"role": "user", "content": _build_user_message(query, sources_text)})

    response = client.chat.completions.create(
        model=config.OPENROUTER_MODEL,
        messages=messages,
        temperature=config.TEMPERATURE,
        max_tokens=config.MAX_OUTPUT_TOKENS,
        response_format={"type": "json_object"},
    )
    return json.loads(response.choices[0].message.content.strip())


# ── Query Rewriting ───────────────────────────────────────

def rewrite_query(query: str, conversation_history: list[dict] = None) -> str:
    """
    Rewrite a conversational query into a dense, context-aware search string.
    Uses the fast REWRITER_MODEL via OpenRouter.
    Falls back to the original query on any error.
    """
    if not conversation_history:
        return query  # No prior context to resolve

    # Build a concise history string from the last 4 turns (truncated to avoid prompt bloat)
    history_str = ""
    for turn in conversation_history[-4:]:
        role = "User" if turn["role"] == "user" else "Al-Ghazali"
        content = turn["content"][:300] + "..." if len(turn["content"]) > 300 else turn["content"]
        history_str += f"{role}: {content}\n"

    user_prompt = (
        f"CHAT HISTORY:\n{history_str}\n\n"
        f"CURRENT USER QUERY:\n{query}\n\n"
        f"Rewrite the CURRENT USER QUERY into a highly specific standalone search string based on the context above."
    )

    try:
        client = _get_openrouter_client()
        response = client.chat.completions.create(
            model=config.REWRITER_MODEL,
            messages=[
                {"role": "system", "content": REWRITER_PROMPT},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.0,
            max_tokens=60,
        )
        raw_content = response.choices[0].message.content
        if not raw_content:
            print("  ⚠ Rewriter returned empty content. Falling back.")
            return query

        rewritten = raw_content.strip()

        # Strip any conversational prefix the model may have hallucinated
        matched = next((p for p in _REWRITER_PREFIXES if rewritten.lower().startswith(p.lower())), None)
        if matched:
            rewritten = rewritten[len(matched):].strip()

        # Remove surrounding quotes if the model wrapped its output
        rewritten = rewritten.strip('"\'')

        print(f"  🔄 Rewritten query: '{rewritten}' (Original: '{query}')")
        return rewritten

    except Exception as e:
        print(f"  ⚠ Rewriter error: {e}. Falling back to original query.")
        return query


# ── Public API ────────────────────────────────────────────

def generate_answer(query: str, retrieved_chunks: list[dict], system_prompt: str,
                    conversation_history: list[dict] = None) -> dict:
    """
    Generate a persona-voiced answer grounded in source chunks.

    Args:
        query: The original user question (not the rewritten search string).
        retrieved_chunks: Chunks from vector store search.
        system_prompt: The complete persona ruleset.
        conversation_history: Previous turns for conversational context (optional).

    Returns:
        Parsed JSON dict with: can_answer, answer_text, citations[], follow_up, closing.
    """
    sources_text = _format_chunks_for_prompt(retrieved_chunks)

    # ── Input Length Guard ────────────────────────────────
    # Conservative token estimate: 4 chars ≈ 1 token (tuned for mixed Arabic/English)
    full_prompt_len = len(query) + len(sources_text) + len(system_prompt)
    if conversation_history:
        full_prompt_len += sum(len(t["content"]) for t in conversation_history)

    estimated_tokens = full_prompt_len // 4
    if estimated_tokens > config.MAX_INPUT_TOKENS:
        print(f"  ✗ Input limit exceeded: ~{estimated_tokens} tokens vs max {config.MAX_INPUT_TOKENS}")
        return _empty_response()

    try:
        result = _generate_openrouter(query, sources_text, system_prompt, conversation_history)

        # ── Normalize field aliases from different model outputs ──
        # Some models return "answer" or "response" instead of "answer_text"
        if "answer" in result and not result.get("answer_text"):
            result["answer_text"] = result["answer"]
        if "response" in result and not result.get("answer_text"):
            result["answer_text"] = result["response"]

        # If the model answered but forgot to set the boolean, infer it
        if result.get("answer_text") and not result.get("can_answer"):
            result["can_answer"] = True

        # Guarantee all required fields are present
        result.setdefault("can_answer", False)
        result.setdefault("answer_mode", "elaborated")
        result.setdefault("quote_primary", "")
        result.setdefault("answer_text", "")
        result.setdefault("citations", [])
        result.setdefault("follow_up", "")
        result.setdefault("closing", "")

        return result

    except json.JSONDecodeError as e:
        print(f"  ✗ JSON parse error: {e}")
        return _empty_response()

    except Exception as e:
        print(f"  ✗ LLM API error: {e}")
        return _empty_response()


def verify_answer(retrieved_chunks: list[dict], generated_answer: dict) -> bool:
    """
    Verification pass: checks whether the generated answer is grounded in sources
    and free of anachronisms (post-505 AH references).

    Uses the fast REWRITER_MODEL to minimize pipeline latency.
    Returns True (grounded) or False (hallucination detected).
    """
    if not config.ENABLE_VERIFICATION:
        return True

    sources_text = _format_chunks_for_prompt(retrieved_chunks)
    answer_text = json.dumps(generated_answer, indent=2, ensure_ascii=False)

    verification_message = (
        f"SOURCE_CHUNKS:\n{sources_text}\n\n---\n\n"
        f"GENERATED_ANSWER:\n{answer_text}\n\n"
        f"Does the GENERATED_ANSWER contain any claims not in the SOURCE_CHUNKS? Respond in JSON."
    )

    try:
        client = _get_openrouter_client()
        response = client.chat.completions.create(
            model=config.REWRITER_MODEL,
            temperature=0.0,
            max_tokens=256,
            messages=[
                {"role": "system", "content": VERIFIER_PROMPT},
                {"role": "user", "content": verification_message}
            ],
            response_format={"type": "json_object"},
        )
        response_text = (response.choices[0].message.content or "").strip()

        if not response_text:
            print("  ⚠ Verification returned empty — passing by default")
            return True

        result = json.loads(response_text)
        hallucinated = result.get("hallucinated", False)

        if hallucinated:
            print(f"  ⚠ Verification FAILED: {result.get('reason', 'Unknown')}")
            return False

        print("  ✓ Verification passed: answer is grounded")
        return True

    except Exception as e:
        print(f"  ⚠ Verification error: {e} — passing by default")
        return True


def _empty_response() -> dict:
    """Return a safe blank response dict when generation fails."""
    return {
        "can_answer": False,
        "answer_text": "I cannot address this matter.",
        "citations": [],
        "follow_up": "",
        "closing": "",
    }
