"""
LLM Client — OpenRouter-only abstraction.
Handles intent routing (fast model), answer generation (large model),
and hallucination + anachronism verification (fast model).
"""

from __future__ import annotations

import json

import core.config as config


# ── Provider Client (lazy-initialized) ───────────────────
_openrouter_client = None


def _get_openrouter_client():
    """Lazy-initialize the OpenRouter client."""
    global _openrouter_client
    if _openrouter_client is None:
        import openai
        _openrouter_client = openai.OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=config.OPENROUTER_API_KEY,
        )
    return _openrouter_client


# ── Prompts ───────────────────────────────────────────────

VERIFIER_PROMPT = """\
You are a fact-checking engine. You will receive:
1. SOURCE_CHUNKS: The original source documents
2. GENERATED_ANSWER: A response generated by another AI

Your task is to ensure the GENERATED_ANSWER is grounded in the SOURCE_CHUNKS.

Rules:
- Ensure that any direct quote in the answer is a valid substring of a SOURCE_CHUNK.
- The answer MAY bridge to a related concept if the exact term is absent from sources, BUT ONLY if it explicitly states the gap (e.g. "This exact term does not appear in my works, but..."). Flag as hallucinated if the answer silently substitutes a different concept without this disclosure.
- Flag as hallucinated if the answer invents historical facts, completely fabricates quotes, or makes claims that directly contradict the provided sources.
- Do NOT flag the answer as hallucinated solely because it uses a conversational or philosophical tone.
- TERMINOLOGY CHECK: If the user query in the GENERATED_ANSWER's context contains a specific Arabic or classical term, verify the answer either (a) directly addresses that term from the sources, or (b) explicitly acknowledges the term is absent and names the nearest related concept. Flag as hallucinated if neither condition is met.
- ANACHRONISM CHECK: Flag as hallucinated if the answer mentions any person, event, or invention that occurred AFTER 505 AH / 1111 CE (e.g. mentions of Ibn Taymiyya, Rumi, modern science, or later history).

Respond in JSON:
{"hallucinated": true/false, "reason": "Brief explanation"}"""

ROUTER_PROMPT = """\
You are a query analysis engine for a classical Islamic text search system.
Analyze the user's query and chat history, then output a JSON object.

JSON schema:
{"intent": "casual|terminology|general_question", "language": "<detected language>", "search_string": "<concise search string>", "requires_rag": true/false}

Rules for search_string:
1. Replace pronouns ("it", "he", "this concept") with the actual subject from chat history.
2. If the user used a specific Arabic/Persian term (e.g. فناء, tawakkul, kashf), PRESERVE it exactly. Do NOT translate or paraphrase it.
3. If the user used a vague modern concept without a classical term, you MAY append the likely equivalent in parentheses — e.g. "intuition (kashf?)".
4. Keep the user's original language context. Do NOT rewrite an Indonesian query into pure Arabic.
5. Remove filler words but preserve all semantic meaning.

Rules for intent:
- "casual": greetings, small talk, "who are you", "thank you" → requires_rag=false
- "terminology": user asks about a SPECIFIC Arabic/classical term → requires_rag=true
- "general_question": broad thematic questions → requires_rag=true

Output ONLY the JSON object.
"""


# ── Source Formatting ─────────────────────────────────────

def _format_chunks_for_prompt(chunks: list[dict]) -> str:
    """Format retrieved chunks as numbered source blocks for the prompt."""
    source_blocks = []
    for i, chunk in enumerate(chunks, 1):
        meta = chunk.get("metadata", {})
        book    = meta.get("book_name", "Unknown")
        chapter = meta.get("chapter", "")
        page    = meta.get("page_number", "")
        volume  = meta.get("volume", "")

        header = f"[SOURCE {i}]"
        if book:    header += f" [BOOK: {book}]"
        if volume:  header += f" [VOLUME: {volume}]"
        if chapter: header += f" [CHAPTER: {chapter}]"
        if page:    header += f" [PAGE: {page}]"

        source_blocks.append(f"{header}\n{chunk['text']}\n[END SOURCE {i}]")

    return "\n\n".join(source_blocks)


def _build_user_message(query: str, sources_text: str) -> str:
    """Build the shared user-turn message injected into every generation call."""
    return (
        f"Here are the SOURCE documents you MUST use to answer:\n\n{sources_text}\n\n---\n\n"
        f"USER QUERY: {query}\n\n"
        f"Remember: Answer using ONLY the sources above. Respond in the required JSON format. Maintain the persona voice."
    )


# ── Generation ────────────────────────────────────────────

def _generate_openrouter(query: str, sources_text: str, system_prompt: str,
                         conversation_history: list[dict] = None) -> dict:
    """Generate answer using OpenRouter."""
    client = _get_openrouter_client()

    messages = [{"role": "system", "content": system_prompt}]
    if conversation_history:
        for turn in conversation_history:
            role = "user" if turn["role"] == "user" else "assistant"
            messages.append({"role": role, "content": turn["content"]})

    messages.append({"role": "user", "content": _build_user_message(query, sources_text)})

    response = client.chat.completions.create(
        model=config.OPENROUTER_MODEL,
        messages=messages,
        temperature=config.TEMPERATURE,
        max_tokens=config.MAX_OUTPUT_TOKENS,
        response_format={"type": "json_object"},
    )
    return json.loads(response.choices[0].message.content.strip())


# ── Intent Routing ────────────────────────────────────────

def analyze_intent(query: str, conversation_history: list[dict] = None) -> dict:
    """
    Analyze the user's query to determine intent, language, and search strategy.
    Uses the fast ROUTER_MODEL via OpenRouter with structured JSON output.
    Returns a dict with: intent, language, search_string, requires_rag.
    """
    default_result = {
        "intent": "general_question",
        "language": "English",
        "search_string": query,
        "requires_rag": True,
    }

    # Build history context if available
    history_str = ""
    if conversation_history:
        for turn in conversation_history[-config.ROUTER_HISTORY_TURNS:]:
            role = "User" if turn["role"] == "user" else "Assistant"
            max_chars = config.ROUTER_TURN_MAX_CHARS
            content = turn["content"][:max_chars] + "..." if len(turn["content"]) > max_chars else turn["content"]
            history_str += f"{role}: {content}\n"

    user_prompt = f"CURRENT USER QUERY:\n{query}"
    if history_str:
        user_prompt = f"CHAT HISTORY:\n{history_str}\n\n{user_prompt}"

    try:
        client = _get_openrouter_client()
        response = client.chat.completions.create(
            model=config.ROUTER_MODEL,
            messages=[
                {"role": "system", "content": ROUTER_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.0,
            max_tokens=150,
            response_format={"type": "json_object"},
        )
        raw = response.choices[0].message.content
        if not raw:
            print("  ⚠ Router returned empty content. Using defaults.")
            return default_result

        result = json.loads(raw.strip())

        # Validate and fill defaults for any missing fields
        result.setdefault("intent", "general_question")
        result.setdefault("language", "English")
        result.setdefault("search_string", query)
        result.setdefault("requires_rag", True)

        # Ensure search_string is never empty
        if not result["search_string"].strip():
            result["search_string"] = query

        print(f"  🧭 Router: intent={result['intent']}, lang={result['language']}, "
              f"rag={result['requires_rag']}, search='{result['search_string']}'")
        return result

    except Exception as e:
        print(f"  ⚠ Router error: {e}. Using defaults.")
        return default_result


def rewrite_query(query: str, conversation_history: list[dict] = None) -> str:
    """
    Legacy wrapper around analyze_intent().
    Returns only the search_string for backward compatibility with api.py.
    """
    if not conversation_history:
        return query  # No prior context to resolve
    result = analyze_intent(query, conversation_history)
    return result.get("search_string", query)


# ── Public API ────────────────────────────────────────────

def generate_answer(query: str, retrieved_chunks: list[dict], system_prompt: str,
                    conversation_history: list[dict] = None) -> dict:
    """
    Generate a persona-voiced answer grounded in source chunks.

    Args:
        query: The original user question (not the rewritten search string).
        retrieved_chunks: Chunks from vector store search.
        system_prompt: The complete persona ruleset.
        conversation_history: Previous turns for conversational context (optional).

    Returns:
        Parsed JSON dict with: can_answer, answer_text, citations[], follow_up, closing.
    """
    sources_text = _format_chunks_for_prompt(retrieved_chunks)

    # ── Input Length Guard ────────────────────────────────
    # Conservative token estimate: 4 chars ≈ 1 token (tuned for mixed Arabic/English)
    full_prompt_len = len(query) + len(sources_text) + len(system_prompt)
    if conversation_history:
        full_prompt_len += sum(len(t["content"]) for t in conversation_history)

    estimated_tokens = full_prompt_len // 4
    if estimated_tokens > config.MAX_INPUT_TOKENS:
        print(f"  ✗ Input limit exceeded: ~{estimated_tokens} tokens vs max {config.MAX_INPUT_TOKENS}")
        return _empty_response()

    try:
        result = _generate_openrouter(query, sources_text, system_prompt, conversation_history)

        # ── Normalize field aliases from different model outputs ──
        # Some models return "answer" or "response" instead of "answer_text"
        if "answer" in result and not result.get("answer_text"):
            result["answer_text"] = result["answer"]
        if "response" in result and not result.get("answer_text"):
            result["answer_text"] = result["response"]

        # If the model answered but forgot to set the boolean, infer it
        if result.get("answer_text") and not result.get("can_answer"):
            result["can_answer"] = True

        # Guarantee all required fields are present
        result.setdefault("can_answer", False)
        result.setdefault("answer_mode", "elaborated")
        result.setdefault("quote_primary", "")
        result.setdefault("answer_text", "")
        result.setdefault("citations", [])
        result.setdefault("follow_up", "")
        result.setdefault("closing", "")

        return result

    except json.JSONDecodeError as e:
        print(f"  ✗ JSON parse error: {e}")
        return _empty_response()

    except Exception as e:
        print(f"  ✗ LLM API error: {e}")
        return _empty_response()


def verify_answer(retrieved_chunks: list[dict], generated_answer: dict) -> bool:
    """
    Verification pass: checks whether the generated answer is grounded in sources
    and free of anachronisms (post-505 AH references).

    Uses the fast ROUTER_MODEL to minimize pipeline latency.
    Returns True (grounded) or False (hallucination detected).
    """
    if not config.ENABLE_VERIFICATION:
        return True

    sources_text = _format_chunks_for_prompt(retrieved_chunks)
    answer_text = json.dumps(generated_answer, indent=2, ensure_ascii=False)

    verification_message = (
        f"SOURCE_CHUNKS:\n{sources_text}\n\n---\n\n"
        f"GENERATED_ANSWER:\n{answer_text}\n\n"
        f"Does the GENERATED_ANSWER contain any claims not in the SOURCE_CHUNKS? Respond in JSON."
    )

    try:
        client = _get_openrouter_client()
        response = client.chat.completions.create(
            model=config.ROUTER_MODEL,
            temperature=0.0,
            max_tokens=256,
            messages=[
                {"role": "system", "content": VERIFIER_PROMPT},
                {"role": "user", "content": verification_message}
            ],
            response_format={"type": "json_object"},
        )
        response_text = (response.choices[0].message.content or "").strip()

        if not response_text:
            print("  ⚠ Verification returned empty — passing by default")
            return True

        result = json.loads(response_text)
        hallucinated = result.get("hallucinated", False)

        if hallucinated:
            print(f"  ⚠ Verification FAILED: {result.get('reason', 'Unknown')}")
            return False

        print("  ✓ Verification passed: answer is grounded")
        return True

    except Exception as e:
        print(f"  ⚠ Verification error: {e} — passing by default")
        return True


def _empty_response() -> dict:
    """Return a safe blank response dict when generation fails."""
    return {
        "can_answer": False,
        "answer_text": "I cannot address this matter.",
        "citations": [],
        "follow_up": "",
        "closing": "",
    }
